name: Deployment triggered tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  call-core-workflow:
    uses: ./.github/workflows/core-flow.yml
    secrets: inherit